Fixes gitlab.com SSL certificate fetching issue
There are a few issues with getting the SSL certificate from gitlab.com
through ssl.get_server_certificate().

First of all, ssl.get_server_certificate() will end up with an
OSError: [Errno 0] Error error, which will cause the Charm to end up
in a BlockedState. This issue is mentioned here [1], and a fix for it
has been included in Python 3.8.6. The GitLab Integrator Charm is using
Python 3.8.5.

Secondly, even in a newer Python, this error is encountered instead:

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

Alternatively, we can use requests.get to get the SSL certificate. However,
the connection and details regarding it will get cleaned up after the request
finishes, so we need to fetch the certificate beforehand. Inspired by [2].

However, since we're not logged in, accessing gitlab.com will redirect us
to about.gitlab.com, which means that we won't actually get gitlab.com's
SSL certificate. For this, we can use gitlab.com/explore, which has no
redirects.

[1] https://bugs.python.org/issue31122
[2] https://stackoverflow.com/questions/16903528/how-to-get-response-ssl-certificate-from-requests-in-python